"""Quitando propiedades a Videojuego

Revision ID: a7cd5e13d89d
Revises: f4b24af1bd7a
Create Date: 2024-07-02 21:22:47.193634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7cd5e13d89d'
down_revision = 'f4b24af1bd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videojuego', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videojuego', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
