"""Agregando nuevas propiedades a Videojuego

Revision ID: f4b24af1bd7a
Revises: ca71fc1357c0
Create Date: 2024-07-02 19:52:24.348908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b24af1bd7a'
down_revision = 'ca71fc1357c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videojuego', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('requisitos_minimos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requisitos_recomendados', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videojuego', schema=None) as batch_op:
        batch_op.drop_column('requisitos_recomendados')
        batch_op.drop_column('requisitos_minimos')
        batch_op.drop_column('precio')

    # ### end Alembic commands ###
